# Generated by Django 5.0.4 on 2024-09-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Configuration',
            fields=[
                ('title', models.TextField(default='')),
                ('gc_id', models.TextField(default='', primary_key=True, serialize=False)),
                ('component_href', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configurations',
            },
        ),
        migrations.CreateModel(
            name='Project_Area',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('projectAreaHref', models.TextField(default='')),
                ('projectAreaAlias', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='HW_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HW_Variant_href', models.TextField(default='')),
                ('HW_Variant_value', models.TextField(default='')),
                ('global_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.global_configuration')),
            ],
        ),
        migrations.CreateModel(
            name='HIL_Setup',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('href', models.TextField(default='')),
                ('host', models.TextField(default='')),
                ('port', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project_area')),
            ],
            options={
                'verbose_name': 'HIL Setup',
                'verbose_name_plural': 'HIL Setups',
            },
        ),
        migrations.AddField(
            model_name='global_configuration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project_area'),
        ),
        migrations.CreateModel(
            name='Sw_Build_RQM',
            fields=[
                ('build_href', models.TextField(primary_key=True, serialize=False)),
                ('build_id', models.TextField(default='')),
                ('build_title', models.TextField(default='')),
                ('global_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.global_configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Environment_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Environment_Configuration_href', models.CharField(default='', max_length=255)),
                ('Test_Environment_Configuration_name', models.CharField(default='', max_length=255)),
                ('global_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.global_configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('tplan_view_id', models.TextField(default='')),
                ('tplan_query_id', models.TextField(default='')),
                ('gc_obj_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testplan', to='home.global_configuration')),
            ],
            options={
                'verbose_name': 'Test Plan',
                'verbose_name_plural': 'Test Plans',
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('test_phase_href', models.TextField(primary_key=True, serialize=False)),
                ('test_phase_title', models.TextField(default='')),
                ('tplan_obj_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.test_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('tsuite_view_id', models.TextField(default='')),
                ('tsuite_query_id', models.TextField(default='')),
                ('tplan_obj_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsuite', to='home.test_plan')),
            ],
            options={
                'verbose_name': 'Test Suite',
                'verbose_name_plural': 'Test Suites',
            },
        ),
        migrations.CreateModel(
            name='Test_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('state', models.CharField(default='', max_length=255)),
                ('tcase_view_id', models.TextField(default='')),
                ('tcase_query_id', models.TextField(default='')),
                ('owner', models.CharField(default='', max_length=255)),
                ('tcase_type', models.CharField(default='', max_length=255)),
                ('functionality', models.CharField(default='', max_length=255)),
                ('tsg_Compliant', models.CharField(default='', max_length=255)),
                ('test_category', models.CharField(default='', max_length=255)),
                ('implementation_path', models.TextField(default='', max_length=255)),
                ('life_cycle_start', models.TextField(default='', max_length=255)),
                ('life_cycle_end', models.TextField(default='', max_length=255)),
                ('tsuite_obj_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase', to='home.test_suite')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
            },
        ),
        migrations.AddConstraint(
            model_name='test_plan',
            constraint=models.UniqueConstraint(fields=('gc_obj_link', 'tplan_query_id'), name='unique_field_testplan'),
        ),
        migrations.AddConstraint(
            model_name='test_suite',
            constraint=models.UniqueConstraint(fields=('tplan_obj_link', 'tsuite_query_id'), name='unique_field_testsuite'),
        ),
        migrations.AddConstraint(
            model_name='test_case',
            constraint=models.UniqueConstraint(fields=('tsuite_obj_link', 'tcase_query_id'), name='unique_field_testcases'),
        ),
    ]
