# Generated by Django 5.0.7 on 2024-09-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_test_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="hil_setup",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iteration",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sw_build_rqm",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hil_setup", name="name", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="iteration",
            name="test_phase_href",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="iteration",
            name="tplan_obj_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iterations",
                to="home.test_plan",
            ),
        ),
        migrations.AlterField(
            model_name="sw_build_rqm",
            name="build_href",
            field=models.TextField(default=""),
        ),
        migrations.AddConstraint(
            model_name="hil_setup",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_field_testsetup"
            ),
        ),
    ]
