# Generated by Django 5.0.4 on 2024-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALM_Server',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('host', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'ALM Server',
                'verbose_name_plural': 'ALM Servers',
            },
        ),
    ]
